### ISSUE TITLE
使用后发现部分功能建议

### ISSUE THREAD

**Issue by loveofyou** [lzq-hopego/get-music-lizhanqi#2]
非常感谢作者的辛苦付出,方便大家寻找自己喜欢的音乐,在使用过程中发现部分功能可优化,提出部分建议,望采纳.
加入文件名过滤特殊字符,防止因文件名内含有特殊字符造成下载失败
```
import re
def validateTitle(title):
    rstr = r"[\/\\\:\*\?\"\<\>\|]"  # '/ \ : * ? " < > |'
    new_title = re.sub(rstr, "_", title)  # 替换为下划线
    return new_title
```
下载前加入已下载文件检测,已下载文件自动跳过
```
    if os.path.exists("./"+fname):
        print("下过了~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
        continue

```
建议下载列表使用逗号作为分隔符,防止因歌曲内部含有空格导致api搜索失败
```
fo=open("get_music.txt",'r',encoding='utf-8')
txt=fo.read().split("\n")
print(txt)
fo.close()


ls=[]
for i in txt:
    ls.append(i.split(","))

```

**Comment by lzq-hopego** [comment]
来信收悉，非常感谢您对这个第三方库的建议。
1、关于文件名在保存时未检查其合法性，属于是v1.0.0版本之后的问题，重构时忘记添加，现已在v1.0.6版本中添加，具体详见download模块
2、关于已经下载过的歌曲会重复下载，现已在v1.0.6版本的download模块增加，在下载之前会检测，并提示是否重新下载
3、关于使用逗号分割的问题其实当初用空格只是为了避免中英文符号带来的不便，没想到给用户带来了不便，现已在v1.0.6版本中采用逗号分割的方式，并支持匹配歌手的功能
最后，感谢您提出的宝贵意见，让get-music-lizhanqi更实用


????
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "lzq-hopego/get-music-lizhanqi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月25日(星期天) 凌晨2:15
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[lzq-hopego/get-music-lizhanqi] 使用后发现部分功能建议 (Issue #2)





 
非常感谢作者的辛苦付出,方便大家寻找自己喜欢的音乐,在使用过程中发现部分功能可优化,提出部分建议,望采纳.
 加入文件名过滤特殊字符,防止因文件名内含有特殊字符造成下载失败
 import re def validateTitle(title):     rstr = r"[\/\\\:\*\?\"\<\&gt;\|]"  # '/ \ : * ? " < &gt; |'     new_title = re.sub(rstr, "_", title)  # 替换为下划线     return new_title  
下载前加入已下载文件检测,已下载文件自动跳过
     if os.path.exists("./"+fname):         print("下过了~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")         continue  
建议下载列表使用逗号作为分隔符,防止因歌曲内部含有空格导致api搜索失败
 fo=open("get_music.txt",'r',encoding='utf-8') txt=fo.read().split("\n") print(txt) fo.close() ls=[] for i in txt:     ls.append(i.split(","))
