### ISSUE TITLE
怎样能批量下载5sing的伴奏？

### ISSUE THREAD

**Issue by benbenlang** [lzq-hopego/get-music-lizhanqi#3]
你好，能不能做到比如输入一个歌手的ID 70733813 把他上传的全部伴奏下载下来，保存名称为
薛之谦-陪你去流浪 伴奏 无人声 伴奏--薛之谦
周兴哲 永不失联的爱伴奏--周兴哲
**“歌曲名“伴奏--”原唱歌手名“**
这样的
<img width="431" alt="image" src="https://user-images.githubusercontent.com/3888076/212538288-df681148-fa4e-46c5-875d-4dcdecdc0691.png">

**Comment by lzq-hopego** [comment]
*使用 **get-music -v** 检查一下版本号更新到最新版本,需要1.2.4版本及以上支持*

* 随便一个文件夹中创建 **get_music.txt**  文件的内容像图片中展示那样，然后在当前目录打开终端(cmd)执行 **get-music -r** 命令等待程序执行完毕即可



![测试图片](https://user-images.githubusercontent.com/94416555/212684306-3994e2fa-3853-4a3e-9461-0af1cf952d9b.jpg)

**Comment by benbenlang** [comment]
> 
还是实现不了“输入一个歌手的ID 70733813 把他上传的全部伴奏下载下来”这样啊
<img width="451" alt="image" src="https://user-images.githubusercontent.com/3888076/218112860-b4b6b8d2-8fde-4ce9-8898-ecb718351cdc.png">
get_music.txt这个文件我建了的

**Comment by benbenlang** [comment]
> _使用 **get-music -v** 检查一下版本号更新到最新版本,需要1.2.4版本及以上支持_
> 
> * 随便一个文件夹中创建 **get_music.txt**  文件的内容像图片中展示那样，然后在当前目录打开终端(cmd)执行 **get-music -r** 命令等待程序执行完毕即可
> 
> ![测试图片](https://user-images.githubusercontent.com/94416555/212684306-3994e2fa-3853-4a3e-9461-0af1cf952d9b.jpg)

还是实现不了“输入一个歌手的ID 70733813 把他上传的全部伴奏下载下来”这样啊

**Comment by lzq-hopego** [comment]
## 确实不能,因为他们平台的网页端无法使用id号搜索，建议使用作者名搜索
> 你可以这样用:
[![ppOIHDU.png](https://s1.ax1x.com/2023/04/12/ppOIHDU.png)](https://imgse.com/i/ppOIHDU)
## 注意你的脚本的版本，如果没有第10个接口，就卸载重装，或者更新
```
get-music -v
```
## 检查版本，版本太低会提示更新命令，因为低版本不支持第十个接口
> 如果你有更好的解决方案可以提出代码😊

**Comment by benbenlang** [comment]
> ## 确实不能,因为他们平台的网页无法使用id号搜索，建议使用作者姓名搜索
> > 你可以这样使用：
> > [![ppOIHDU.png](https://camo.githubusercontent.com/d629a85b7ba82669b2b5ec9375109678ccfdb7080bd9cb73ca9548130dc886c2/68747470733a2f2f73312e617831782e636f6d2f323032332f30342f31322f70704f494844552e706e67)](https://imgse.com/i/ppOIHDU)
> 
> ## 注意你的脚本的版本，如果没有第10个接口，就担载重装，或者更新
> ```
> get-music -v
> ```
> 
> ## 检查版本，版本太低会提示更新命令，因为低版本不支持第10个接口
> > 如果你有更好的解决方案可以提供代码😊
1，好像还是不行，我用上传歌曲的歌手名称搜索了，搜不出来她的全部伴奏（图片）
2，如果先输入歌曲名，再选择下载的话没有试听，这样盲下不好用的。
3，另外保存的也不是“歌曲名-演唱歌手名”这个格式，现在是“歌曲名-上传的人”这个格式，一首伴奏上传的人不重要，谁唱的很重要
4，我搜了个“越剧”，搜出来的歌曲名都只有越剧2个字，是不是不完整？
<img width="691" alt="image" src="https://user-images.githubusercontent.com/3888076/236292067-c03bff49-e793-4a36-9e2c-65f3606f1975.png">

**Comment by lzq-hopego** [comment]
> 本脚本不能完全代替官方的下载渠道返回的信息，因此不建议使用get-music进行下载，我编写本脚本的初衷仅仅是为了解决不知道哪个平台有歌曲的版权的问题，并不是为了下载，而且对于5sing平台的数据不是那么的方便获取，因此使用他们官方提供的效果更好，你也可以发现我的其他接口返回的数据都和官方的数据有差异，这是无法避免的
### 接下来回答你问题
> 1、歌手名字搜索的问题我注意到了，因为5sing平台细分的翻唱、原创以及伴奏中细分的节点太多，为了一时间的返回速度考虑和不规范的返回数据，会造成有些无法解析，默认搜索的是他们的歌曲，而不是细分的演唱等等。
> 2、我也注意到盲下的问题了，你或许可以尝试一下我的另一个项目get-music-lizhanqi-gui,它会提供一个gui可供你轻度试听，注意，下载歌曲不是本脚本的主题。
> 3、保存的名字已做更改，和你说的一致，但是会导致一个问题，就是如果下载同一首歌同一个原唱作业的伴奏没有上传者作为区分，可能会导致下载多个时下载成一个文件，并不会创建多个文件。
> 4、问题已在新版本中修复(1.2.6)
- 最后:其实不建议使用本脚本下载，把它当作搜索器即可
