### ISSUE TITLE
5sing翻唱好像不能用

### ISSUE THREAD

**Issue by neroxiangkongyue** [lzq-hopego/get-music-lizhanqi#4]
显示 [无法返回数据或接口失效,或者您的网络未连接]

**Comment by lzq-hopego** [comment]
- 你好，请问是搜索了什么歌曲而导致的呢，我这里测试是可以正常返回的
![image](https://github.com/lzq-hopego/get-music-lizhanqi/assets/94416555/0c61f2d3-17cb-4822-b4c1-ebfec69db99b)

**Comment by neroxiangkongyue** [comment]
![image](https://github.com/lzq-hopego/get-music-lizhanqi/assets/47469588/8937ed84-a393-4e1e-a69f-59a155d61650)
 结果如上.但是我搜 11  是有结果的
![image](https://github.com/lzq-hopego/get-music-lizhanqi/assets/47469588/527994bc-0ad7-4bf9-ab08-fc451cc32aba)
不知道是不是我哪里没有用对

**Comment by neroxiangkongyue** [comment]
我发现有时候可以 
![image](https://github.com/lzq-hopego/get-music-lizhanqi/assets/47469588/8e228db0-cfd2-4f38-ac48-61c4f090614e)
有时候又不行😭😭
![image](https://github.com/lzq-hopego/get-music-lizhanqi/assets/47469588/fe1be28e-c47d-4919-bb65-71173a8d917c)

**Comment by lzq-hopego** [comment]
### 问题收到，我分析了一下原因
> 编码问题
![屏幕截图 2023-07-28 205220](https://github.com/lzq-hopego/get-music-lizhanqi/assets/94416555/25fe9bfb-ef12-4760-b9d3-e39558e0f645)
- 使用11这首歌可以搜索到歌曲是因为11在提交url时不用转码，而使用剑伤搜索时因为是中文，原先的程序没有转码的代码，因此会导致直接无法发送请求，而直接报错(无法返回的错误)，在v1.2.7版本中已经修复此问题
>  时不时无响应，超时问题
- 使用正确的名字搜索时，会有时无法返回数据的问题是因为超时的问题，在新版本中已经将超时时间提高到了3s（默认为1s，提升超时时间的弊端是网络延迟大时返回数据的数据将远远大于3s）

> 修复后的版本，测试样张
![屏幕截图 2023-07-28 205450](https://github.com/lzq-hopego/get-music-lizhanqi/assets/94416555/82f5f375-6353-4c6a-81e0-5f5eeb0f7d88)
- 关于版本更新，使用get-music -v检查是否有更新，更新使用pip命令进行更新
