### ISSUE TITLE
关于更合理封装模块的建议

### ISSUE THREAD

**Issue by godisboy0** [lzq-hopego/get-music-lizhanqi#5]
感谢大佬的工作。我只是个小菜鸡。在使用过程中，发现大佬的很多模块是面向终端使用封装的，比如
1. 有些方法直接向终端输出；
2. 有些方法中还有sys.exit() 这类方法的调用；
3. 没有缓存系统，对于每次调用都是全新的远端请求，效率较低。
对于第三方想在你的工作上继续开发（比如我最近在做一个给家人玩的机器人），调用起来就不太方便。

不知道大佬是否有意在现在的工作的基础上，开发一个面向二次开发的包？封装地更适合二次开发一点。
这方面我愿意和大佬合作，在你的工作基础上再做一层开发。不知道大佬是否有意。

**Comment by lzq-hopego** [comment]
您提出的问题都很致命对于这个库来说。短期内不会计划进行再次封装，会对一些不合理的功能修改，例如获取歌单的那些。
    1、对于有些方法面向终端输出的问题，是可以被解决的，每个模块的search方法没有输出，只有返回，因此，二次开发不必考虑此问题，对于get_music_url方法是直接返回的，get_music_pic和get_music_lrc可以传reture_url=True避免无返回值直接保存的问题，可以参考我最近上传的示例
    2、对于sys.exit()方法调用的问题，可以对你的代码进行try...except进行捕获，不过触发sys.exit()方法一般是没有任何有效数据返回的，可以直接try捕获
    3、这个问题有想过，但是目前来说是不打算继续开发下去的(只会偶尔修修小bug)，我也知道继续开发可以带来更高的自定义，代理、更高的响应速度和更高的效率
关于二次开发，你可以参考我最近上传的示例.py，示例2.py，我不知道您使用本库如何结合的机器人，但是我想只要支持python3.7可能就能通过代码导入的方式实现基础功能的自定义，如果您要使用本库二次开发并打包，建议使用from..import..语法这样可以避免控制台输出logo，也很感谢您提出的问题！

**Comment by godisboy0** [comment]
感谢~
